import type { SpaceObject } from './types';

export const ORBIT_COLORS: Record<string, string> = {
  LEO: '#4fc3f7',
  MEO: '#81c784',
  GEO: '#ffb74d',
  HEO: '#e57373',
};

export const COUNTRY_FLAG: Record<string, string> = {
  USA: '🇺🇸',
  RUS: '🇷🇺',
  CHN: '🇨🇳',
  ISS: '🌍',
  ESA: '🇪🇺',
  JPN: '🇯🇵',
  IND: '🇮🇳',
};

export const spaceObjects: SpaceObject[] = [
  {
    id: 'iss',
    name: 'ISS (ZARYA)',
    noradId: 25544,
    type: 'PAYLOAD',
    country: 'ISS',
    launchDate: '1998-11-20',
    lat: 51.6,
    lon: -45.3,
    altitudeKm: 408,
    orbitType: 'LEO',
    inclination: 51.64,
    periodMin: 92.9,
    description: 'International Space Station — crewed orbital research laboratory operated by NASA, ESA, JAXA, CSA, and Roscosmos.',
  },
  {
    id: 'hubble',
    name: 'HST (Hubble)',
    noradId: 20580,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '1990-04-24',
    lat: 28.5,
    lon: 12.1,
    altitudeKm: 547,
    orbitType: 'LEO',
    inclination: 28.47,
    periodMin: 95.4,
    description: 'Hubble Space Telescope — NASA/ESA flagship optical telescope in low Earth orbit.',
  },
  {
    id: 'gps-iif-2',
    name: 'GPS IIF-2',
    noradId: 35752,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2011-07-16',
    lat: 55.3,
    lon: 98.2,
    altitudeKm: 20200,
    orbitType: 'MEO',
    inclination: 55.0,
    periodMin: 717.9,
    description: 'GPS Block IIF navigation satellite, part of the US Global Positioning System constellation.',
  },
  {
    id: 'intelsat-18',
    name: 'INTELSAT 18',
    noradId: 37834,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2011-10-05',
    lat: 0.04,
    lon: 180.0,
    altitudeKm: 35786,
    orbitType: 'GEO',
    inclination: 0.03,
    periodMin: 1436.1,
    description: 'Geostationary communications satellite serving Asia-Pacific and Pacific Ocean regions.',
  },
  {
    id: 'landsat-8',
    name: 'LANDSAT 8',
    noradId: 39084,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2013-02-11',
    lat: -74.2,
    lon: 160.4,
    altitudeKm: 705,
    orbitType: 'LEO',
    inclination: 98.2,
    periodMin: 98.9,
    description: 'Earth observation satellite for land cover and land use change monitoring, operated by NASA and USGS.',
  },
  {
    id: 'starlink-1130',
    name: 'STARLINK-1130',
    noradId: 44932,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2020-01-29',
    lat: 38.7,
    lon: -77.4,
    altitudeKm: 550,
    orbitType: 'LEO',
    inclination: 53.0,
    periodMin: 95.6,
    description: 'SpaceX Starlink broadband internet constellation satellite, shell 1 (53° inclination).',
  },
  {
    id: 'tiangong',
    name: 'CSS (TIANHE)',
    noradId: 48274,
    type: 'PAYLOAD',
    country: 'CHN',
    launchDate: '2021-04-29',
    lat: 41.5,
    lon: 72.3,
    altitudeKm: 400,
    orbitType: 'LEO',
    inclination: 41.48,
    periodMin: 92.5,
    description: 'Chinese Space Station core module Tianhe — crewed orbital laboratory operated by CNSA.',
  },
  {
    id: 'noaa-20',
    name: 'NOAA-20 (JPSS-1)',
    noradId: 43013,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2017-11-18',
    lat: -89.1,
    lon: -45.0,
    altitudeKm: 824,
    orbitType: 'LEO',
    inclination: 98.7,
    periodMin: 101.4,
    description: 'NOAA polar-orbiting weather and environmental satellite — monitors atmosphere, oceans, and land.',
  },
  {
    id: 'molniya-3-50',
    name: 'MOLNIYA 3-50',
    noradId: 25485,
    type: 'PAYLOAD',
    country: 'RUS',
    launchDate: '1998-07-01',
    lat: 63.4,
    lon: 40.8,
    altitudeKm: 39300,
    orbitType: 'HEO',
    inclination: 63.2,
    periodMin: 717.8,
    description: 'Russian Molniya-class communications satellite in highly elliptical orbit — designed for high-latitude coverage.',
  },
  {
    id: 'sentinel-2a',
    name: 'SENTINEL-2A',
    noradId: 40697,
    type: 'PAYLOAD',
    country: 'ESA',
    launchDate: '2015-06-23',
    lat: 12.1,
    lon: 33.5,
    altitudeKm: 786,
    orbitType: 'LEO',
    inclination: 98.6,
    periodMin: 100.6,
    description: 'ESA Copernicus Earth-observation satellite — high-resolution multispectral imaging for land monitoring.',
  },
  {
    id: 'ses-1',
    name: 'SES-1',
    noradId: 36516,
    type: 'PAYLOAD',
    country: 'USA',
    launchDate: '2010-04-24',
    lat: 0.0,
    lon: -101.0,
    altitudeKm: 35786,
    orbitType: 'GEO',
    inclination: 0.02,
    periodMin: 1436.1,
    description: 'SES geostationary communications satellite covering the Americas.',
  },
  {
    id: 'debris-fengyun',
    name: 'FENGYUN 1C DEB',
    noradId: 29228,
    type: 'DEBRIS',
    country: 'CHN',
    launchDate: '2007-01-11',
    lat: 25.0,
    lon: 102.0,
    altitudeKm: 847,
    orbitType: 'LEO',
    inclination: 98.8,
    periodMin: 102.1,
    description: 'Debris fragment from the 2007 Chinese anti-satellite test on Fengyun-1C — one of the largest debris-generating events in history.',
  },
];
